
`r thetitle`
============

`r format(Sys.time(), "%d %B %Y")`
----------------------------------

```{r, echo=FALSE}
#Load files:
load_files <- function(in_file){
    header <- read.table(in_file, nrows = 1, header = FALSE, sep ='\t', stringsAsFactors = FALSE)
    pos <- grep("Clone count", header)
    num_items <- length(header)
    if(pos == 2){
      # clones <- read.table(pipe(paste("cut -f2,6-8", in_file, collapse=" ")), header=TRUE, sep="\t",
      #                    colClasses = c("integer", "character", "character", "character"))
      #Make compatible with windows
      clones <- read.table(in_file, header=TRUE, sep="\t", colClasses = c("NULL", "integer", rep("NULL", 3), "character", "character", "character", rep("NULL", num_items-8)))
    }else if(pos == 1){
      # clones <- read.table(pipe(paste("cut -f1,5-7", in_file, collapse=" ")), header=TRUE, sep="\t",
      #                    colClasses = c("integer", "character", "character", "character"))
      clones <- read.table(pipe(paste("cut -f1,5-7", in_file, collapse=" ")), header=TRUE, sep="\t",
                         colClasses = c("integer", rep("NULL", 3), "character", "character", "character", rep("NULL", num_items-8)))
    }
    
    
    for(i in 1:nrow(clones)){
        top_hit_v <- (strsplit(clones$All.V.hits[i], "\\*")[[1]][1])
        clones$top_hit_v[i] <- top_hit_v
        top_hit_j <- (strsplit(clones$All.J.hits[i], "\\*")[[1]][1])
        clones$top_hit_j[i] <- top_hit_j
        
    }
    return(clones)
}

JV <- load_files(vj_clones)
JV_fl <- load_files(vj_filt_clones)
JV_un <- load_files(vj_unprod_clones)



```

```{r, echo=FALSE}
if("ggplot2" %in% rownames(installed.packages()) == FALSE) {
  install.packages("ggplot2")
}else{
  require(ggplot2)
}
# ggplot() +
# 	geom_density(aes(x = Clone.count,y = ..density..*100),data=JV,adjust = 1) +
# 	geom_vline(data=JV1_bw2_IMGT_clones_readIds,xintercept = 9.0,linetype = 2) +
# 	scale_x_continuous(limits = c(0,13)) +
# 	theme_classic()
# 
# low_clone_cut <- function(in_data, title){
#   #calculate local minimum within the first 30th quartile
#   d <- density(in_data$Clone.count, bw = "sj")
#   #30th quartile
#   v <- optimize(approxfun(d$x, d$y), interval=c(1,as.numeric(quantile(in_data$Clone.count, prob = 0.3))))$minimum
#   p <- ggplot() + 
#     geom_density(aes(x = Clone.count,y = ..density..), data=in_data, adjust = 0.1) + 
#     geom_vline(data=in_data, xintercept= v, linetype = 2) + 
#     scale_x_continuous(limits = c(-10,max(in_data$Clone.count))) +
#     theme_classic() +
#     xlab(label = 'Clone count') +
#     ylab(label = 'Clonotype density') +
#     ggtitle(title)
#   print(p)
#   return(v)
# } 
# 
# cutoff_JV <- low_clone_cut(JV, "JV")
# cat("Cutoff:", cutoff_JV)
# 
# 
# JV <- JV[JV$Clone.count >= cutoff_JV, ]
# JV_fl <- JV_fl[JV_fl$Clone.count >= cutoff_JV, ]
# JV_un <- JV_un[JV_un$Clone.count >= cutoff_JV, ]

```




```{r, echo=FALSE}
#Get IGHV gene names and order from IMGT:
if("XML" %in% rownames(installed.packages()) == FALSE) {
  install.packages("XML")
}else{
  require(XML)
}

IGH <- "http://www.imgt.org/IMGTrepertoire/index.php?section=LocusGenes&repertoire=GenePositions&species=mouse&group=IGH"

IGH_table = readHTMLTable(IGH, header=FALSE, which=1,stringsAsFactors=FALSE)

IGH_table <- IGH_table[-c(1,2),]
names(IGH_table) <- IGH_table[1,]
IGH_table <- IGH_table[-1,]

IGHV_order_JV <- matrix(c(rev(IGH_table$`IMGT Gene`[1:182]), rep(rep(0,182), 6)), 
                        nrow=182, ncol=7, dimnames=list(NULL, c("ordered_IGHV", 
                                                                "Clone_count_all", 
                                                                "Clonotype_count_all",
                                                                "Clone_count_productive", 
                                                                "Clonotype_count_productive",
                                                                "Clone_count_unproductive", 
                                                                "Clonotype_count_unproductive")))

#Sum number of clones in all files:
sum_clones <- function(IGHV_list, column, in_file, ...){
    in_files <- list(in_file, ...)
    for(i in 1:(nargs()-2)){
        for(x in 1:nrow(in_files[[i]])){
            row_pos <- which(in_files[[i]]$top_hit_v[x] == IGHV_list)
            IGHV_list[row_pos, column] <- sum(as.numeric(IGHV_list[row_pos, column]), 
                                          in_files[[i]]$Clone.count[x])
        }
    }
    return(IGHV_list)
}

sum_clonotypes <- function(IGHV_list, column, in_file, ...){
    in_files <- list(in_file, ...)
    for(i in 1:(nargs()-2)){
        for(x in 1:nrow(in_files[[i]])){
            row_pos <- which(in_files[[i]]$top_hit_v[x] == IGHV_list)
            IGHV_list[row_pos, column] <- sum(as.numeric(IGHV_list[row_pos, column]), 
                                         1)
        }
    }
    return(IGHV_list)
}

IGHV_order_JV <- sum_clones(IGHV_order_JV, 2, JV)
IGHV_order_JV <- sum_clonotypes(IGHV_order_JV, 3, JV)
IGHV_order_JV <- sum_clones(IGHV_order_JV, 4, JV_fl)
IGHV_order_JV <- sum_clonotypes(IGHV_order_JV, 5, JV_fl)
IGHV_order_JV <- sum_clones(IGHV_order_JV, 6, JV_un)
IGHV_order_JV <- sum_clonotypes(IGHV_order_JV, 7, JV_un)


#Matrix to data.frame:
df_IGHV_order_JV <- as.data.frame(IGHV_order_JV, stringsAsFactors=FALSE)

for(i in 2:7){
    df_IGHV_order_JV[,i] <- as.numeric(df_IGHV_order_JV[,i])
}

#Need to specify levels for order to be maintained in ggplot
df_IGHV_order_JV$ordered_IGHV <- factor(df_IGHV_order_JV$ordered_IGHV, 
                                        levels = df_IGHV_order_JV$ordered_IGHV)

```

**Plot clone and clonotype V gene usage counts:**
```{r, fig.width = 20, fig.height = 5, echo=FALSE}
for(i in 2:7){
    print(names(df_IGHV_order_JV)[i])
    p <- ggplot(df_IGHV_order_JV, aes(x = ordered_IGHV, y = df_IGHV_order_JV[,i])) + 
        geom_bar(stat="identity") +
        theme_classic() +
        theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5)) +
        xlab(label = 'IGHV') +
        ylab(label = 'Read count') +
        scale_y_continuous(expand = c(0, 0))
    print(p)
}
```

**V clone and clonotype summary table:**
```{r, echo=FALSE}
kable(df_IGHV_order_JV)
```
